"""add user_id to reading sessions

Revision ID: 0c2631ac500d
Revises: 
Create Date: 2026-06-24 19:53:20.646333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2631ac500d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.create_index('idx_books_user_id', 'books', ['user_id'], unique=False)
    
    op.add_column('user_streak', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index('user_streak_user_id_unique', 'user_streak', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_foreign_key(None, 'user_streak', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_streak', type_='foreignkey')
    op.drop_index('user_streak_user_id_unique', table_name='user_streak', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_column('user_streak', 'user_id')
    op.create_index(op.f('idx_reading_sessions_created_at'), 'reading_sessions', ['created_at'], unique=False)
    op.drop_index('idx_books_user_id', table_name='books')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
